### ISSUE TITLE
It doesnt work on LG G3

### ISSUE THREAD

**Issue by CherryAnt** [fbricker/extension-android-immersive#1]
I just try on LG G3, just writing on project.xml:
<haxelib name="extension-android-immersive" />

I think I have to do nothing else... isnt it?
I use landscape mode and i see at right the menus of the mobile

**Comment by joackobengochea** [comment]
Do you have Android 4.4.2 or any other update or mod? i'm gonna take a look at these

**Comment by CherryAnt** [comment]
It has 5.0
I just tested on my real LG G3, it is a extension i was looking for during long time
I am going to test on different versions of genymotion emulator and i will inform you

**Comment by joackobengochea** [comment]
great! i'll see what can i do to include more devices.

**Comment by joackobengochea** [comment]
Are you using the sdk version 19? OpenFl uses sdk 16 by default, we forgot to put in the readme that targeting the android sdk version 19 is needed for the extension to work. try adding 

``` xml
<section if="android">
    <android target-sdk-version="19" />
</section>
```

to the project.xml

**Comment by CherryAnt** [comment]
i got:
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19

but the menu shows at right black with 3 points that is for each menu button

**Comment by joackobengochea** [comment]
that is the android low profile mode, for devices that can't hide the soft buttons. Did you change the target as i said in the previous comment?

**Comment by CherryAnt** [comment]
I use haxeflixel and in project.xml i got:
    
    android target-sdk-version="19" />
    haxelib name="extension-android-immersive" />

I delete the < at start line because with it, the comment hides that line
what do you mean with low profile mode?

**Comment by joackobengochea** [comment]
Some devices can't hide the soft keys. instead of the immersive mode that hides the entire nav bar, the low profile mode makes the 3 keys turn into 3 dots, that are less noticeable.

**Comment by CherryAnt** [comment]
well for me it does the same with your extension and without, that is 3 dots... lg g3 hide soft keys because i try some games like clash of clans that hides all nav bar and show it in transparent mode

**Comment by joackobengochea** [comment]
ok, i'll test with an android 4.4.2 and see what can i do

**Comment by CherryAnt** [comment]
Great thanks a lot!!!

**Comment by joackobengochea** [comment]
i have updated the extension, please download the git version and tell me if it solves your problem.. thanks!

**Comment by CherryAnt** [comment]
Hi,
Well seems the same as before....
Is there anyway i can log on console if it calls hideSystemUI function?
I try edit your java adding:
Log.v("calling hideSystemUI");
Log.d("calling hideSystemUI");
Log.i("calling hideSystemUI");
....
on onStart function but never shows on logcat that info

**Comment by joackobengochea** [comment]
Try Log.d("some tag" , "the actual message" );

**Comment by CherryAnt** [comment]
Yes i try all of this:
        Log.v("vInfo", "hideSystemUI call");
        Log.d("dInfo", "hideSystemUI call");
        Log.i("iInfo", "hideSystemUI call");
        Log.w("wInfo", "hideSystemUI call");
        Log.e("eInfo", "hideSystemUI call");
and i will not find on logcat

**Comment by joackobengochea** [comment]
did you build and install again after adding those logs?
you have to execute  buildAndInstall.sh or .bat to apply the changes you made

**Comment by CherryAnt** [comment]
Well i really dont understand what to do i add:
haxelib git extension-android-immersive https://github.com/fbricker/extension-android-immersive.git
then i add the extension on my project.xml
if i edit some file its supposed it read directly from the change i made when i compile

**Comment by joackobengochea** [comment]
not really, it reads from the library installed in the libs path, but not
from the git folder you are changing. to make the library change, you need
to install the changed library again, by running the .sh or .bat provided
in the git folder

2015-06-15 16:34 GMT-03:00 Jordi Cerezo Formiga notifications@github.com:

**Comment by CherryAnt** [comment]
Well its not working for me on any way i try to execute the sh but the logs functions are not called

**Comment by fbricker** [comment]
Hi, please note that when you log from Java using Log.d("XXXX", "YYYYY");, you won't see that log on the same output as where you see the trace("XXXXXX") outputs.

To be able to see the Java Log.d("XXXX", "YYYYY"); I recommend you to open the android log console and filter those logs to find them.

From command line (on linux or mac), you can use

```
adb logcat  | grep "XXXXXX"
```

Or on Windows, Linux and Mac, you can open Android Device Monitor and see the logs in there.
Android Device Monitor should be in:

```
%ANDROID_SDK_FOLDER%/tools/monitor 
```

Please check this and tell us if you get any sign of the function being called :)

Thanks!

**Comment by CherryAnt** [comment]
no i have no any message, its like never call that class
i am using haxeflixel i supposed it must be not the problem

**Comment by CherryAnt** [comment]
yes!!!!
I create a project with just openfl and its working!!!
How can i do using with haxeflixel?
Thanks

**Comment by joackobengochea** [comment]
We are testing with HaxeFlixel apps and is working fine... Maybe you have some error in the project.xml of the haxflixel app?

**Comment by CherryAnt** [comment]
I create a new haxeflixel project and... seems work xd
I dont know what happen in my current project that dont work...
Otherway i see that on openfl project and haxeflixel new project just adding:
the target sdk version  on project.xml the immersive works even if i dont include your extension!!!
I think you must try to make that your extension works without the sdk version... because it reduce the project to number of smartphones

**Comment by fbricker** [comment]
Hi, thing is that OpenFL already has the immersive mode enabled for 4.4 and higher, but it has some issues.

So, if you just add the API LEVEL 19 to your project, your will have immersive mode en Android 4.4+, but:
- You'll not have immersive on lower versions.
- If for any reason you leave the immersive mode (like opening google play games screens, the native share dialog, the IAP dialig, etc,... or sometimes also just minimize and re-open your game), your game will came back without the immersive mode, having the software buttons on top of the UI.

So, this extension intends to add immersive mode on most android versions + fix the issues on newer versions when you loose the immersive mode for some reason.

Unfortunately, if you want to enable immersive mode on android 4.4+, you need to use API LEVEL 19 (you don't have the necessary API on lower versions). But this should not cause your game to be restricted to newer devices (as those APIs are backward compatible). In fact we do have games compiled with API 19 working on devices with Android 2.3 :+1: 

Finally: I don't know why the immersive works on your new projects and not on your wold-ones. Maybe if you send us a copy of your project.xml we can check what's going on.

Thanks!

**Comment by CherryAnt** [comment]
Thanks for info, i understand now!!! 
We change the target sdk but not the min target sdk 
About my old project problem... probably is a stupid line code... just need to find

**Comment by CherryAnt** [comment]
Hi,
Finally i found the error... I dont know why, when i compiled the app it will no update mobile version... then i was always running the same old version...
Thanks a lot for patience!!!

**Comment by fbricker** [comment]
Never mind :)
